### ISSUE TITLE
Use underscore style

### ISSUE THREAD

**Issue by Kodrafo** [Haufe-Lexware/Support-API#1]
Please use the underscore style instead of camelCase.
https://github.com/Haufe-Lexware/api-style-guide/blob/master/rest-principles.md#resource-naming

**Comment by hlgr360** [comment]
Ditto .. it appears that new fields are being added in CamelCase and not using the underscore style as defined by our API style guide. I am also seeing the use of dash, instead of underscore.

**Comment by hlgr360** [comment]
@Kodrafo to clarify if this issue needs to be addressed or not. If not please close with the reasoning why this API gets an exception. Otherwise please address.
